//> Core data structures and base helpers for Chunks
import "raylib.h" as rl;
import "blocks.zc";

raw {
    typedef struct Chunk Chunk;
    typedef struct ChunkMeshes ChunkMeshes;
    typedef struct Plant Plant;
}

extern fn abs(v: int) -> int;

def RENDER_DISTANCE = 15;
def CHUNK_MAP_SIZE = 32; 
def MAX_CHUNKS = 1024;   
def CHUNK_HEIGHT = 128;

struct Plant {
    x: float; y: float; z: float;
    plant_type: int;
}

struct ChunkMeshes {
    opq_mesh: rl::Mesh; water: rl::Mesh;
    has_opaque: int; has_water: int;
}

struct Chunk {
    blocks: int[16][128][16];
    light: int[16][128][16];
    plants: Plant[64];
    plant_count: int;
    chunk_mesh: rl::Mesh; chunk_model: rl::Model;
    water_mesh: rl::Mesh; water_model: rl::Model;
    water_mesh_built: int;
    plant_mesh: rl::Mesh; plant_model: rl::Model;
    plant_mesh_built: int;
    grass_deco_mesh: rl::Mesh; grass_deco_model: rl::Model;
    grass_deco_built: int;
    mesh_dirty: int; mesh_built: int;
    x: int; z: int; locked: int;
    last_water_tick: double;
}

fn is_transparent(b: int) -> int {
    if b == BLOCK_AIR || (b >= 10 && b <= 14) || b == 17 || b == BLOCK_TALLGRASS || b == BLOCK_LEAVES || b == BLOCK_WATER || b == BLOCK_WATER_2 || b == BLOCK_WATER_1 || b == 18 { return 1; }
    return 0;
}

fn get_chunk_index(cx: int, cz: int) -> int {
    let mx = cx & (CHUNK_MAP_SIZE - 1);
    let mz = cz & (CHUNK_MAP_SIZE - 1);
    return mz * CHUNK_MAP_SIZE + mx;
}

fn get_block(chunks: Chunk*, num_chunks: int, x: int, y: int, z: int) -> int {
    if y < 0 || y >= CHUNK_HEIGHT { return BLOCK_AIR; }
    
    let cx = x >> 4;
    let cz = z >> 4;
    let lx = x & 15;
    let lz = z & 15;

    let idx = get_chunk_index(cx, cz);
    if chunks[idx].x == cx && chunks[idx].z == cz {
        return chunks[idx].blocks[lx][y][lz];
    }
    
    // EL FIX MAESTRO: Si el bloque está fuera del mundo cargado, 
    // devolvemos un bloque de "Barrera" (255) en lugar de Aire.
    // Esto impide que el agua y la luz intenten calcularse hacia el infinito.
    return 255; 
}

fn set_block(chunks: Chunk*, num_chunks: int, x: int, y: int, z: int, type: int) {
    if y < 0 || y >= CHUNK_HEIGHT { return; }

    let cx = x >> 4;
    let cz = z >> 4;
    let lx = x & 15;
    let lz = z & 15;

    let idx = get_chunk_index(cx, cz);
    if chunks[idx].x == cx && chunks[idx].z == cz {
        chunks[idx].blocks[lx][y][lz] = type;
    }
}