
import "persistence_defs.zc";
import "chunk.zc";
import "lighting.zc"; // for recalculate_chunk_lighting

fn handle_light_request(req: any, chunks: Chunk*, num_chunks: int) {
    raw {
        IORequest* r = (IORequest*)req;
        if (chunks != NULL) {
            Chunk* c = &chunks[r->target_idx];
            
            if(r->type == 4) { // REQ_LIGHT_RECALC
                recalculate_chunk_lighting(c, chunks, num_chunks);
            }
            else if(r->type == 5) { // REQ_LIGHT_PROPAGATE
                propagate_light_in_chunk(c, chunks, num_chunks);
            }
            
            r->io_status = 2; // COMPLETED
        } else {
            r->io_status = 3; // FAILED
        }
    }
}
