//> Core Rendering Module (Umbrella wrapper)
// Importamos los subsistemas para que quien importe 'rendering.zc' tenga acceso a todo
import "assets.zc";
import "environment.zc";
import "clouds.zc";

// Función auxiliar para inicializar todo el motor gráfico de una sola vez
fn init_rendering() {
    init_textures(); // Carga las texturas y shaders (de assets.zc)
    init_clouds();   // Genera el mesh de las nubes (de clouds.zc)
}