//> Mesh Uploading to GPU
import "raylib.h" as rl;
import "../world/chunk_core.zc";
import "../render/rendering.zc";

fn upload_chunk_mesh(c: Chunk*, meshes: ChunkMeshes) {
    if c == NULL { return; }

    // Silenciamos los INFO de Raylib para evitar el spam en consola
    rl::SetTraceLogLevel(rl::LOG_WARNING);

    if c.mesh_built == 1 {
        rl::UnloadModel(c.chunk_model);
        c.mesh_built = 0;
    }
    if c.water_mesh_built == 1 {
        rl::UnloadModel(c.water_model);
        c.water_mesh_built = 0;
    }

    if meshes.has_opaque == 1 {
        rl::UploadMesh(&meshes.opq_mesh, false);
        c.chunk_mesh = meshes.opq_mesh;
        c.chunk_model = rl::LoadModelFromMesh(meshes.opq_mesh);
        c.mesh_built = 1;
        
        c.chunk_model.materials[0].shader = get_shader_lighting();
        c.chunk_model.materials[0].maps[rl::MATERIAL_MAP_DIFFUSE].texture = get_tex_atlas();
    } else {
        c.chunk_mesh = rl::GenMeshCube(0.0, 0.0, 0.0);
        c.chunk_model = rl::LoadModelFromMesh(c.chunk_mesh);
        c.mesh_built = 1; 
    }

    if meshes.has_water == 1 {
        rl::UploadMesh(&meshes.water, false);
        c.water_mesh = meshes.water;
        c.water_model = rl::LoadModelFromMesh(meshes.water);
        c.water_mesh_built = 1;
        
        c.water_model.materials[0].shader = get_shader_lighting();
        c.water_model.materials[0].maps[rl::MATERIAL_MAP_DIFFUSE].texture = get_tex_atlas();
    } else {
        c.water_mesh_built = 0; 
    }
    
    c.power_source_count = meshes.power_source_count;
    for i in 0..meshes.power_source_count {
        c.power_sources[i] = meshes.power_sources[i];
    }
    
    c.mesh_dirty = 0;
}

fn upload_plant_mesh(c: Chunk*, mesh: rl::Mesh) {
    if c == NULL { return; }
    
    // Silenciamos también la subida de plantas
    rl::SetTraceLogLevel(rl::LOG_WARNING);

    if c.plant_mesh_built == 1 {
        rl::UnloadModel(c.plant_model);
        c.plant_mesh_built = 0;
    }
    
    if mesh.vertexCount > 0 {
        rl::UploadMesh(&mesh, false);
        c.plant_mesh = mesh;
        c.plant_model = rl::LoadModelFromMesh(mesh);
        c.plant_mesh_built = 1;
        
        c.plant_model.materials[0].shader = get_shader_grass();
        c.plant_model.materials[0].maps[rl::MATERIAL_MAP_DIFFUSE].texture = get_tex_grass();
    } else {
        c.plant_mesh_built = 0;
    }
}