//> Chunk Rendering Methods
import "raylib.h" as rl;
import "chunk_core.zc";
import "../render/rendering.zc"; // Access to shaders and textures
import "../render/grass_deco.zc";

impl Chunk {
    fn draw_opaque(self, chunks: Chunk*, num_chunks: int, builds_in_frame: int*, max_builds: int, player_cx: int, player_cz: int) {
        if self.x == -9999 { return; }
        
        if self.mesh_built == 1 {
            let gx_base = (float)(self.x * 16);
            let gz_base = (float)(self.z * 16);
            
            let offset = rl::Vector3{ x: gx_base, y: 0.0, z: gz_base };
            rl::DrawModel(self.chunk_model, offset, 1.0, rl::WHITE);
        }
    }

    fn draw_transparent(self, chunks: Chunk*, num_chunks: int, player_cx: int, player_cz: int, grass_dist: float) {
        if self.x == -9999 { return; }
        
        let gx_base = (float)(self.x * 16);
        let gz_base = (float)(self.z * 16);
        let offset = rl::Vector3{ x: gx_base, y: 0.0, z: gz_base };
        
        // 1. Water
        if self.water_mesh_built == 1 {
            if self.water_model.meshCount > 0 {
                rl::DrawModel(self.water_model, offset, 1.0, rl::WHITE);
            }
        }
        
        // 2. Plants
        if self.plant_mesh_built != 0 {
            set_grass_use_tex(1);
            rl::DrawModel(self.plant_model, offset, 1.0, rl::WHITE);
        }
        
        // 3. Grass Decorations (LOD)
        if grass_dist > 0.0 {
            let dx = (float)player_cx - (gx_base + 8.0);
            let dz = (float)player_cz - (gz_base + 8.0);
            let dist_sq = dx * dx + dz * dz;
            let dist_thresh = grass_dist * grass_dist;
            
            if dist_sq < dist_thresh {
                 if self.grass_deco_built == 0 && self.mesh_built != 0 {
                    build_grass_decorations(self, chunks, num_chunks); // <--- CORREGIDO (sin &)
                 }
                
                if self.grass_deco_built != 0 {
                    set_grass_use_tex(0);
                    rl::DrawModel(self.grass_deco_model, offset, 1.0, rl::WHITE);
                }
            }
        }
    }
}